spring.application.name=CampusEventManagement
spring.datasource.url=jdbc:mysql://localhost:3306/campus_event
spring.datasource.username=root
spring.datasource.password=anruth

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false